sudo: required

arch:
    packages:
        - sdl2
        - qt5-base
        - assimp
        - boost
    script:
        - git clone https://github.com/alecthomas/entityx
        - mkdir -p entityx/build
        - cd entityx/build
        - cmake -DCMAKE_INSTALL_PREFIX=/usr/ ..
        - make
        - sudo make install
        - cd ../..
        - mkidr build
        - cd build
        - cmake ..
        - make
        
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

