language: cpp
sudo: required

compiler: 
    -clang
    -gcc
os: linux

arch: 
    packages:
        - boost
        - qt5-base
        - sdl2
        - glm
        - box2d
        - cmake
    script:
        # TINYOBJLOADER
        - git clone https://github.com/syoyo/tinyobjloader
        - mkdir tinyobjloader/build
        - cd tinyobjloader/build
        - pwd 
        - pwd
        - cmake -DCMAKE_INSTALL_PREFIX=/usr/ ..
        - make
        - sudo make install
        - cd ../..
        # anax
        - git clone https://github.com/miguelmartin75/anax
        - mkdir anax/build
        - cd anax/build
        - cmake  -DCMAKE_INSTALL_PREFIX=/usr/ ..
        - make
        - sudo make install
        - cd ../..
        # gentlemanly_engine
        - git clone https://github.com/gentlemans/gentlemanly_engine
        - mkdir gentlemanly_engine/build
        - cd gentlemanly_engine/build
        - cmake ..
        - make 

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
