sudo: required
language: cpp

matrix:
  include:
    - compiler: gcc
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libwayland-dev
      env: COMPILER=g++-6
    - compiler: clang
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libwayland-dev
      env: COMPILER=clang++-3.6
    - compiler: clang
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - libwayland-dev
      env: COMPILER=clang++-3.7
    - compiler: clang
    - os: osx


script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_FLAGS="-Wall" -DCMAKE_CXX_COMPILER=$COMPILER
  - make
