sudo: required
language: cpp

matrix:
  include:
    - compiler: gcc
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
            - libwayland-dev
      env:
        - COMPILER=g++-6
        - BUILD_TYPE=Debug
    - compiler: clang
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libwayland-dev
      env:
        - COMPILER=clang++-3.6
        - BUILD_TYPE=Debug
    - compiler: clang
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - libwayland-dev
      env:
        - COMPILER=clang++-3.7
        - BUILD_TYPE=Debug
    - os: osx
      env: BUILD_TYPE=Debug

    - compiler: gcc
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
            - libwayland-dev
      env:
        - COMPILER=g++-6
        - BUILD_TYPE=Release
    - compiler: clang
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55/cmake-3.x
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - libwayland-dev
      env:
        - COMPILER=clang++-3.6
        - BUILD_TYPE=Release
    - compiler: clang
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
            - cmake
            - libwayland-dev
      env:
        - COMPILER=clang++-3.7
        - BUILD_TYPE=Release
    - arch: 
        packages: 
          - cmake
          - emscripten
        script:
          - mkdir build
          - cd build
          - cmake .. -DCMAKE_TOOLCHAIN_FILE=usr/lib/emscripten/cmake/Modules/Platform/Emscripten.cmake
          - make
      script: 
        - 'ARCH_TRAVIS_MIRROR=http://mirrors.abscission.net/archlinux curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash'
    - os: osx
      env: BUILD_TYPE=Release


script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_CXX_FLAGS="-Wall" -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - make
