language: cpp
os: 
    - linux
    - osx

compiler:
    - gcc
    - clang
    
before_install:
    - apt-get update -qq
    - apt-get install libboost-all-dev libglm-dev
    # TinyObjLoader
    - git clone https://github.com/syoyo/tinyobjloader -b v0.9.21
    - cd tinyobjloader
    - mkdir build
    - cd build
    - cmake ..
    - make install
    
script: 
    - mkdir build
    - cd build
    - cmake ..
    - make test
