language: cpp
sudo: required
dist: trusty
compiler: 
    -clang
    -gcc
os: linux
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libboost-filesystem-dev
    # TINYOBJLOADER
    - 
