sudo: required

arch:
    packages:
        - sdl2
        - qt5-base
        - cmake
        - assimp
        - glm
        - boost
    script:
        - cmake -DENTITYX_BUILD_TESTING=OFF .
        - make
        
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

