sudo: required

language: c++

dist: trusty

before_install:
    - git clone https://github.com/alecthomas/entityx
    - mkdir -p entityx/build
    - cd entityx/build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr/ ..
    - make
    - sudo make install
    - cd ../..

script:
    - mkdir build
    - cd build
    - cmake ..
    - make

