sudo: required

arch:
    packages:
        - sdl2
        - qt5-base
        - cmake
        - assimp
        - boost
    script:
        - mkdir build
        - cd build
        - cmake ..
        - make
        
script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

