sudo: required

language: cpp

arch:
    packages:
        - sdl2
        - qt5-base
        - cmake
        - assimp
        - glm
        - boost
        - glu
        - libvorbis
        - openal
        - libogg
    script:
        - cmake -DCMAKE_CXX_FLAGS="-Wall" .
        - make
        

os: 
  - linux
  - osx

script:
  - 'if [ "$TRAVIS_OS_NAME" = "linux" ]; then'
  - 'curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash'
  - else
  - brew install boost sdl2 cmake
  - cmake . -DCMAKE_CXX_FLAGS="-Wall"
  - make
  - fi

