language: cpp
sudo: required

compiler: 
    -clang
    -gcc
os: linux

arch: 
    packages:
        - boost
        - qt5-base
        - sdl2
        - glm
        - box2d
        - cmake
    before_script:
        - sudo apt-get -y update -qq
        - sudo apt-get -y install g++-5 libboost-filesystem-dev qtbase5-dev libsdl2-dev > /dev/null
        # TINYOBJLOADER
        - git clone https://github.com/syoyo/tinyobjloader
        - mkdir tinyobjloader/build
        - cd tinyobjloader/build
        - cmake -DCMAKE_INSTALL_PREFIX=/usr/ ..
        - make
        - sudo make install
        - cd ../..
        # anax
        - git clone https://github.com/miguelmartin75/anax
        - mkdir anax/build
        - cd anax/build
        - cmake  -DCMAKE_INSTALL_PREFIX=/usr/ ..
        - make
        - sudo make install
        - cd ../..

    script:
        - mkdir build
        - cd build
        - cmake ..
        - make 

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
