version: 1.0.{branch}.{build}

max_jobs: 2

image: Visual Studio 2015

init: 
    - pwd
    - cd %APPVEYOR_BUILD_FOLDER%/..
    - pwd
    - ps: wget http://heanet.dl.sourceforge.net/project/boost/boost/1.62.0/boost_1_62_0.zip -OutFile c:/boost.zip
    - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem
    - ps: '[System.IO.Compression.ZipFile]::ExtractToDirectory("c:/boost.zip", "c:/boost/")'
    - cd c:/boost/boost_1_62_0/
    - bootstrap
    - b2 toolset=msvc-14.0 link=static address-model=64 variant=debug variant=release --with-system --with-filesystem
    - cd %APPVEYOR_BUILD_FOLDER%/..
    - ps: wget https://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip -OutFile c:/sdl2.zip
    - ps: '[System.IO.Compression.ZipFile]::ExtractToDirectory("c:/sdl2.zip", "c:/sdl2")'



install:
    - pwd
    - mkdir build
    - cd build
    - '"C:\Program Files (x86)\cmake\bin\cmake.exe" .. -G"Visual Studio 14 Win64" -DBoost_DIR=../boost/boost_1_62_0/ -DBoost_FILESYSTEM_LIBRARY_DEBUG=c:/boost/boost_1_62_0/lib/stage/libboost_filesystem-vc140-mt-gd-1_62.lib -DBoost_FILESYSTEM_LIBRARY_RELEASE=c:/boost/boost_1_62_0/lib/stage/libboost_filesystem-vc140-mt-1_62.lib -DBoost_SYSTEM_LIBRARY_DEBUG=c:/boost/boost_1_62_0/lib/stage/libboost_system-vc140-mt-gd-1_62.lib -DBoost_SYSTEM_LIBRARY_RELEASE=c:/boost/boost_1_62_0/lib/stage/libboost_system-vc140-mt-1_62.lib'

platform: x64

build:
    parallel: true
    project: build/gentlemanly_engine.sln

