version: 1.0.{branch}.{build}

max_jobs: 2

image: Visual Studio 2015

init: 
    - ps: $dir=pwd
    - cd %APPVEYOR_BUILD_FOLDER%/..
    - ps: wget http://heanet.dl.sourceforge.net/project/boost/boost/1.62.0/boost_1_62_0.zip -OutFile c:/boost.zip
    - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem
    - ps: '[System.IO.Compression.ZipFile]::ExtractToDirectory("c:/boost.zip", "c:/")'
    - ps: mv C:/boost_1_62_0 c:/boost
    - cd c:/boost/
    - bootstrap
    - b2 toolset=msvc-14.0 link=static address-model=64 variant=debug variant=release --with-system --with-filesystem
    - cd %APPVEYOR_BUILD_FOLDER%/..
    - ps; mv stage/lib lib 
    - ps: wget https://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip -OutFile c:/sdl2.zip
    - ps: '[System.IO.Compression.ZipFile]::ExtractToDirectory("c:/sdl2.zip", "c:/")'
    - mv C:/sdl2-2.0.4 C:/sdl2
    - ps: ls C:/
    - ps: ls C:/sdl2
    - ps: cd $dir
    

install:
    - mkdir build
    - cd build
    - '"C:\Program Files (x86)\cmake\bin\cmake.exe" .. -G"Visual Studio 14 Win64"'

platform: x64

build:
    parallel: false
    project: build/gentlemanly_engine.sln

