version: 1.0.{branch}.{build}

max_jobs: 2

image: Visual Studio 2015

init: 
    - ps: wget http://heanet.dl.sourceforge.net/project/boost/boost/1.62.0/boost_1_62_0.zip -OutFile boost.zip
    - ps: Add-Type -AssemblyName System.IO.Compression.FileSystem
    - ps: '[System.IO.Compression.ZipFile]::ExtractToDirectory("boost.zip", "boost/")'
    - cd boost/boost_1_62_0/
    - bootstrap
    - b2 toolset=msvc-14.0 link=static address-model=64 variant=debug variant=release --with-system --with-filesystem
    - cd ../..
    - ps: wget https://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip -OutFile sdl2.zip
    - ps: '[System.IO.Compression.ZipFile]::ExtractToDirectory("sdl2.zip", "sdl2/")'



install:
    - mkdir build
    - cd build
    - '"C:\Program Files (x86)\cmake\bin\cmake.exe" .. -G"Visual Studio 14 Win64" -DBoost_DIR=../boost/boost_1_62_0/ -DBoost_FILESYSTEM_LIBRARY_DEBUG=../boost/boost_1_62_0/lib/stage/libboost_filesystem-vc140-mt-gd-1_62.lib -DBoost_FILESYSTEM_LIBRARY_RELEASE=../boost/boost_1_62_0/lib/stage/libboost_filesystem-vc140-mt-1_62.lib -DBoost_SYSTEM_LIBRARY_DEBUG=../boost/boost_1_62_0/lib/stage/libboost_system-vc140-mt-gd-1_62.lib -DBoost_SYSTEM_LIBRARY_RELEASE=../boost/boost_1_62_0/lib/stage/libboost_system-vc140-mt-1_62.lib -DSDL2_LIBRARY=../sdl2/SDL2-2.0.4/lib/x64/SDL2.lib -DSDL2_INCLUDE_DIR=../sdl2/SDL2-2.0.4/include'

platform: x64

build:
    - parallel: true
    - project: build/gentlemanly_engine.sln

